# This is a basic workflow that is manually triggered

name: Manual Startup

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Starting Download Thread for Visa/MasterCard'
        # Default value if no value is explicitly provided
        default: 'Say Anything'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  trydownloading:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Clone Github Repository
      run: git clone https://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@github.com/OttomanZ/SuperCardSet.git 
    - name: Show Contents
      run: cd SuperCardSet/ && ls -l
    - name: Install Dependencies
      run: cd SuperCardSet/
      run: sudo apt-get update && sudo apt-get install python3 && sudo apt-get install python3-pip && pip3 install -r requirements.txt
    - name: Start Download Instance
      run: cd SuperCardSet/
      run: python3 generate_data.py
    - name: Completed
      run: echo "Completed"
      
